### ISSUE TITLE
Wrong behavior in specific case of CtUnion

### ISSUE THREAD

**Issue by rafaeleyng** [ctessum/go.clipper#16]
Hello and thanks for the awesome lib 😄 

## The problem

I'm experiencing weird behavior when unioning some polygons in specific cases.

The example below seems correct at a first inspection, unioning these polygons (the black rectangle around is not part of the union):
  ![polygons0](https://user-images.githubusercontent.com/4842605/115936449-a7498000-a46b-11eb-9554-20492b9431c2.png)

results in this polygon:  
![union0](https://user-images.githubusercontent.com/4842605/115936471-b4666f00-a46b-11eb-9aaa-8e675c93a988.png)

Looking closer, we see:
![polygons1](https://user-images.githubusercontent.com/4842605/115936527-dbbd3c00-a46b-11eb-97d8-e1aae02bd8bc.png)

becoming:
![union1](https://user-images.githubusercontent.com/4842605/115936541-eaa3ee80-a46b-11eb-831c-5b994a48145b.png)

which is not what I would expect, because the edge from the orange polygon is being ignored there in the union result.

## The code

My code is equivalent to:

```golang
clip := clipper.NewClipper(clipper.IoNone)
clip.AddPaths(paths, clipper.PtSubject, true)
result, ok := clip.Execute1(clipper.CtUnion, clipper.PftNonZero, clipper.PftNonZero)
// omitting the `ok` handling here

// generates the first image that I showed in the description
outputPaths(paths)

// generates the second image that I showed in the description
outputResult(result)
```

Out of ideas, I tried some combinations of using `PtClip`, like using `PtClip` for all the paths, or `PtSubject` for the first and `PtClip` for the others. I always got the same result.

My original polygons are defined with `float64` coordinates, but I convert to Clipper's representation by scaling to a factor. I've tried scaling factors from `1e4` to `1e10`, but the problem persists.

---

So, how could I obtain the result that I expect (that is, including that "diagonal" of the orange polygon in the resulting path)?

If it would help, I can try to set up a repo containing this very particular example 🙂

**Comment by rafaeleyng** [comment]
I created this repo to reproduce the test case: https://github.com/rafaeleyng/clipper-union-bug

**Comment by rafaeleyng** [comment]
I've tested against the C++ implementation of Clipper, and it produced the expected output:

![image](https://user-images.githubusercontent.com/4842605/116263666-ee778f80-a74f-11eb-880e-3251fa246c9e.png)

Instead of what I got with the Go version:

![image](https://user-images.githubusercontent.com/4842605/115936541-eaa3ee80-a46b-11eb-831c-5b994a48145b.png)

So I guess it is a problem specific to the Go version.

**Comment by rafaeleyng** [comment]
Hi @ctessum! 😃 

I also tried with the JavaScript version of Clipper, and it worked as expected (added the example to my repo). So indeed it seems an issue particular to the Go port, or just some change that wasn't yet introduced on the Go version. I see that the Go library is based upon version `6.1.5` while my tests were again `6.4.2` of the other libraries.

My intention is to continue this investigation and possibly contribute with a fix (that can be as much as making the Go lib become up to the latest version of the reference library again, or something smaller if is just a bug in the port).

Are you willing to accept that kind of contribution? Also, I'm taking any suggestions that might help with that!

**Comment by rafaeleyng** [comment]
For further reference, I just tested:
- with the C++ lib with versions `6.1.3` and `6.4.2`
- with the JavaScript lib with versions `6.1.3` and `6.4.2`

And both gave me the result I expected. I will start debugging the Go version then.

**Comment by ctessum** [comment]
Hi,

Thanks for this information. I'm not currently actively maintaining this repo, but I'm glad to take any contributions!

**Comment by rafaeleyng** [comment]
Ok, I'm actively investigating the bug, I expect to have a fix in the next few days.

**Comment by rafaeleyng** [comment]
I think I found the solution, I'm opening 3 PRs (one specific to this problem + 2 others not directly related)
