### ISSUE TITLE
Hi! i try use go.clipper 

### ISSUE THREAD

**Issue by airof98** [ctessum/go.clipper#2]
i changed clipper_test.go
`"github.com/ctessum/carto" -> "github.com/ctessum/geom/carto"`

but while `go get github.com/ctessum/geom/carto`
github.com/golang/freetype/truetype/face.go:254: undefined: font.Metrics

**Comment by ctessum** [comment]
It should work now. You can open another issue if it doesn't. These days, however, I have been using this library instead: https://github.com/akavel/polyclip-go

**Comment by ctessum** [comment]
also, maybe try 'go get **-u** github.com/ctessum/geom/carto'?

**Comment by airof98** [comment]
works thanks~
